In [1]:
#data processing and 
#building the linear regression for multiple variables

In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model


In [3]:
df = pd.read_csv("home_prices.csv")

In [4]:
df

area  bedrrom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [12]:
mg = df.bedrrom.median()


In [14]:
mf = int(mg)
mf

3

In [20]:
print(mf)

3


In [17]:
df['bedrrom'] = df.bedrrom.fillna(mf)

In [19]:
print(df)

   area  bedrrom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.5   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000


In [21]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrrom','age']],df.price)

LinearRegression()

In [22]:
reg.coef_

array([    198.47159002, -116583.73881651,  -14267.77585936])

In [23]:
reg.predict([[3000,3,40]])

array([330999.05823262])

In [24]:
reg.predict([[3000,3,5]])

array([830371.21331031])